import csv
import requests
import time
from pathlib import Path
from typing import List, Dict

# this is the script to download the pdfs from the csv file which is generated by the main.py file
# the downloaded pdfs go into the pdfs folder
# keep a valid csv file path and in the read csv file function, read the csv file and return the list of papers with title, code and pdf link which is used to download the pdfs

PDF_DIR = Path("pdfs")
CSV_FILE = "2024_2025_50.csv"

def read_csv_file(csv_file: str) -> List[Dict]:
    papers = []
    try:
        with open(csv_file, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                papers.append({
                    'code': row['Code'],
                    'title': row['Title'],
                    'pdf_url': row['Research Paper Link']
                })
        print(f"Read {len(papers)} papers from CSV")
        return papers
    except Exception as e:
        print(f"Error reading CSV: {e}")
        return []

def download_pdf(url: str, filename: str) -> bool:
    try:
        PDF_DIR.mkdir(exist_ok=True)

        print(f"Downloading: {filename}")
        response = requests.get(url, timeout=30)
        response.raise_for_status()

        filepath = PDF_DIR / filename
        with open(filepath, 'wb') as f:
            f.write(response.content)

        print(f"Downloaded: {filename}")
        return True
    except Exception as e:
        print(f"Error downloading {filename}: {e}")
        return False

def download_all_pdfs(papers: List[Dict]):
    print(f"Starting download of {len(papers)} PDFs...")

    for i, paper in enumerate(papers):
        filename = f"ICLR_{paper['code'].replace('-', '_')}.pdf"
        success = download_pdf(paper['pdf_url'], filename)

        if success:
            print(f"✓ Downloaded {i+1}/{len(papers)}: {paper['code']}")
        else:
            print(f"✗ Failed {i+1}/{len(papers)}: {paper['code']}")

        if i < len(papers) - 1:
            time.sleep(1)

    print("All downloads completed!")

def main():
    csv_file = CSV_FILE
    papers = read_csv_file(csv_file)
    download_all_pdfs(papers)

if __name__ == "__main__":
    main()
